{
    'name': 'Odoo Procedures Manual',
    'author': 'Ousseynou kane',
    'depends': ['base', 'base_automation', 'web', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'views/workflow_views.xml',
        'views/workflow_stage_views.xml',
        'views/workflow_state_views.xml',
        'views/workflow_transition_views.xml',
        'views/workflow_stage_transition_views.xml',
        'views/workflow_job_views.xml',
        'views/workflowable_type_views.xml',
        'views/workflow_procedure_views.xml',
        'wizard/workflow_procedure_duration_wizard_views.xml',
        'views/workflow_procedure_stage_views.xml',
        'wizard/workflow_procedure_stage_duration_wizard_views.xml',
        'views/workflow_procedure_stage_acl_views.xml',
        'wizard/workflow_procedure_stage_acl_wizard_views.xml',
        'views/workflow_procedure_cycle_views.xml',
        'wizard/workflow_procedure_cycle_duration_wizard_views.xml',
        'views/workflow_procedure_cycle_stage_views.xml',
        'views/workflow_procedure_cycle_stage_transition_views.xml',
        'wizard/workflow_procedure_cycle_stage_duration_wizard_views.xml',
        'views/workflow_procedure_transition_views.xml',
        'views/workflow_procedure_stage_transition_views.xml',
        'views/workflow_procedure_stage_transition_acl_views.xml',
        'wizard/workflow_procedure_stage_transition_acl_wizard_views.xml',
        'views/workflow_procedure_execution_views.xml',
        'wizard/workflow_procedure_execution_duration_wizard_views.xml',
        'views/workflow_user_views.xml',
        'views/workflow_user_role_views.xml',
        'views/workflow_procedure_collision_views.xml',
        'views/workflow_process_views.xml',
        'views/workflow_process_stage_views.xml',
        'views/workflow_process_stage_acl_views.xml',
        'views/workflow_process_cycle_views.xml',
        'views/workflow_process_cycle_stage_views.xml',
        'views/workflow_process_cycle_stage_transition_views.xml',
        'views/workflow_process_transition_views.xml',
        'views/workflow_process_stage_transition_views.xml',
        'views/workflow_process_stage_transition_acl_views.xml',
        'views/workflow_process_execution_views.xml',
        'wizard/workflow_process_execution_wizard_views.xml',
        'views/workflowable_views.xml',
        'wizard/workflowable_manual_procedure_trigger_wizard_views.xml',
        'views/workflowable_position_views.xml',
        'views/configuration_menu_actions.xml',
        'views/routes_menu_actions.xml',
        'views/procedures_menu_actions.xml',
        'views/processes_menu_actions.xml',
        'views/processes_actions.xml',
        'views/menu.xml'
    ],
    'installable': True,
    'application': True,
    'assets': {
        'web.assets_backend': [
            'nxd_workflow/static/src/js/form/**/*',
        ]
    },
    'images': [
        'images/main_1.png', 'images/main_2.png', 'images/main_screenshot.png'
    ],
    'license': 'OPL-1',
    'price': 410.00,
    'currency': 'EUR'
}
